name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Set up the Google Cloud SDK
      - uses: google-github-actions/setup-gcloud@v3
        with:
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
      
      # Deploy the file to the bucket
      - run: gsutil cp spark_etl/main.py gs://stack-data-pipeline-gcp-mg-combustiveis-brasil-pyspark-code/main.py